### ISSUE TITLE
Unknown column 'wlp_talk_updated' in 'field list'

### ISSUE THREAD

**Issue by szotsaki** [mediawiki4intranet/Wikilog#10]
When I updated Wikilog to this Github version from MW version, I ran maintenance/update.php.

It returned with the following error:
```
Creating page_last_visit table ...done.
Creating wikilog_subscriptions table ...done.
Creating wikilog_talkinfo table ...A database query error has occurred.
Query: INSERT INTO `esl_wikilog_talkinfo` ( wti_page, wti_talk_updated, wti_num_comments )
 SELECT wlp_page, wlp_talk_updated, wlp_num_comments FROM `esl_wikilog_posts`

Function: DatabaseBase::sourceFile( [...]/extensions/Wikilog/archives/patch-talkinfo.sql )
Error: 1054 Unknown column 'wlp_talk_updated' in 'field list' (localhost)

Regenerating wlc_thread for Wikilog comments
```

And indeed, I only have a `wlp_updated` column, not `wlp_talk_updated` in `*wikilog_posts`.

**Comment by vitalif** [comment]
You're right, my wikilog was trying to migrate its own field that's not present in the original version. I've just commited the fix, but you should drop your wikilog_talkinfo table before re-running update with the modified version to get it filled correctly.
