### ISSUE TITLE
Update Wikilog captcha handling

### ISSUE THREAD

**Issue by tgr** [mediawiki4intranet/Wikilog#11]
See https://gerrit.wikimedia.org/r/#/c/289250 - from MediaWiki 1.27 on, `passCaptcha[Limited]()` should be replaced with `passCaptcha[Limited]FromRequest($request, $user)`.

**Comment by vitalif** [comment]
See the latest commit, is it ok?

**Comment by tgr** [comment]
Looks good, thanks!
