### ISSUE TITLE
Strange formatting

### ISSUE THREAD

**Issue by BrunoRobert** [mediawiki4intranet/Wikilog#12]
Thank you for that extension. I have a problem (self explanatory):
[https://wiki.greifswald.freifunk.net/wiki/Blog:Freifunk_Greifswald](https://wiki.greifswald.freifunk.net/wiki/Blog:Freifunk_Greifswald)

Bruno

**Comment by vitalif** [comment]
Very strange. Again, first try to update Wikilog to master branch from here.

**Comment by BrunoRobert** [comment]
Aftre upgrading the Mystery is gone.

**Comment by vitalif** [comment]
The problem is the version in official MediaWiki repositories is old and unsupported... only some Wikimedia developers change old deprecated API calls to newer ones in that repo
