### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by BrunoRobert** [mediawiki4intranet/Wikilog#13]
Sorry, but the is a second problem when I try to submit a comment:
Fatal error: Cannot access protected property LinksUpdate::$mDb in /.../mediawiki/extensions/Wikilog/WikilogLinksUpdate.php on line 44

Bruno

**Comment by vitalif** [comment]
Are you sure you're using the latest version from master branch from here (github)? The described issue is the same as #5, but it's already fixed.

**Comment by BrunoRobert** [comment]
You are right, it was an older version. But after installing the actual I get a database error when I try to submit a blog entry.

**Comment by vitalif** [comment]
run `php maintenance/update.php` after upgrade

**Comment by BrunoRobert** [comment]
I found an older string in the conf (Wikilog::setupNamespace( 102, 'Blog', 'Blog_talk' ); and chagend it to Wikilog::setupBlogNamespace(102);.
No error now but Special:Version shows 1.2.0 now (formerly 1.3.0).

Bruno

**Comment by vitalif** [comment]
This version was in fact forked from 1.2.0 and version number was not updated after forking :)
Ok, I've just updated the version to 2.0 to make it clear that this version is newer... even if someone in wikimedia will decide to "release" 1.4.0 or so :D
