### ISSUE TITLE
MediaWiki internal error.

### ISSUE THREAD

**Issue by BrunoRobert** [mediawiki4intranet/Wikilog#14]
Can you give me a hint, how to embed a Wikilog?
If I try out the example I get an error: MediaWiki internal error.

Bruno

**Comment by vitalif** [comment]
Do you mean you want to include Special:Wikilog on other page?
I'm doing it like this:
`{{Special:Wikilog/Template:BlogInformerLine/25/sort=wti_talk_updated}}`
Template:BlogInformerLine contains the following code in my case:
`* {{#if:{{{dateInFuture|}}}|[[File:PinIcon_Scala.png|16px|link=]] '''|}}[[{{{page}}}|{{#regex:{{{title}}}|/^(\d{4}-\d{2}-\d{2}[\s:]*)?/|{{{date}}}:&#x20;}}]] &larr; [[{{{wikilogPage}}}|{{{wikilogTitle}}}]]{{#if:{{{ncomments|}}}|, {{{talkUpdatedDate}}} &mdash; [[{{{talkpage}}}|{{{ncomments}}} комментари{{PLURAL:{{{ncomments}}}|й|я|ев}}]]|}}{{#if:{{{dateInFuture|}}}|'''|}}`

**Comment by BrunoRobert** [comment]
Thank your very much. I have again learned something ;)
