### ISSUE TITLE
Call to undefined method WikiPage::getText()

### ISSUE THREAD

**Issue by szotsaki** [mediawiki4intranet/Wikilog#19]
Since 1.21 `WikiPage::getText()` is [deprecated](https://doc.wikimedia.org/mediawiki-core/1.27.0/php/classWikiPage.html#ab574733a13d9eb6b707430819c766808). I found that (at least) in WikilogUtils.php on line 213 it's used and with v1.29 the page doesn't load.

**Comment by FlorianSW** [comment]
Also tracked in: https://phabricator.wikimedia.org/T179532

**Comment by szotsaki** [comment]
This issue is solved.
