### ISSUE TITLE
PHP Fatal error:  Call to undefined method Wikilog::setupBlogNamespace()

### ISSUE THREAD

**Issue by zsdedan** [mediawiki4intranet/Wikilog#6]
Hi.
When I try to run php update.php I got this message:
PHP Fatal error:  Call to undefined method Wikilog::setupBlogNamespace() in /hosting/www/clients/client3/web53/web/LocalSettings.php on line 253

In LocalSettings.php on line 253 is
Wikilog::setupBlogNamespace( 100 );

Help me to fix it.

MW 1.24.2
Wikilog 1.2.0

**Comment by vitalif** [comment]
Did you include Wikilog.php?

**Comment by zsdedan** [comment]
Yes.

But I found a solution. In discussion on mediawiki page of this extension I found fix. Using

Wikilog::setupNamespace( 100, 'Lenta', 'Обсуждение' ); 

works for me.

**Comment by vitalif** [comment]
O_O It's very strange, look at Wikilog class in Wikilog.php - these two functions are just nearby. Are you sure you're using this (github) version? Wikilog that's still present in Wikimedia repositories is the older one.

**Comment by zsdedan** [comment]
I have installed latest Wikilog 1.3 from mediawiki git, but problem with 
<code>PHP Fatal error: Call to undefined method Wikilog::setupBlogNamespace()</code>
is still present when I run update.php.

If I use "fix" (bad fix, I think), I can't get normal work of comments feature. I have got a blank page when I wrote first comment. And when I click on "1 комментарий", got blank page too.

So problem is no solved.

Если есть возможность общаться на русском, прошу её использовать.

**Comment by vitalif** [comment]
Есть конечно =))

Короче, в wikimedia git версия неправильная. Там осталась версия, которую делал оригинальный автор, моих правок там нет. Потому у тебя и метода не хватает.

**Comment by zsdedan** [comment]
Установил Wikilog отсюда (github), всё заработало. Благодарю за ответы.
